name: fitness_tracking_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.1
  get: ^4.6.6
  provider: ^6.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner:
  flutter_gen_runner:  
  flutter_lints: ^4.0.0

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80

  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    
  colors:
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true

  assets:
    - assets/colors/